services:
  app:
    build: .
    volumes:
      - ./apps/web:/LibreLingo/librelingo-web:Z
      - ./apps/docs/build:/LibreLingo/build/docs:Z
      - ./scripts:/LibreLingo/scripts:Z
      - ./src:/LibreLingo/app:Z # Python tools
      - ./docs:/LibreLingo/docs:Z
      - ./courses:/LibreLingo/courses:Z
    command: ['tail', '-f', '/dev/null']
    ports:
      - '8000:8000' # for mkdocs serve
    #environment:
  web:
    build:
      dockerfile: Dockerfile_web
      context: .
    volumes:
      - ./apps/web/src/courses:/app/apps/web/src/courses:Z
      - node_modules:/app/node_modules
    #  - ./apps/docs/build:/LibreLingo/build/docs
    #  - ./scripts:/LibreLingo/scripts
    #  - ./src:/LibreLingo/app # Python tools
    #  - ./docs:/LibreLingo/docs
    #  - ./courses:/LibreLingo/courses
    ports:
      - '5173:5173'
    #environment:

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules