services:
  app:
    build: .
    volumes:
      - ./apps/web:/LibreLingo/librelingo-web
      - ./apps/docs/build:/LibreLingo/build/docs
      - ./src:/LibreLingo/app # Python tools
      - ./docs:/LibreLingo/docs
      - ./courses:/LibreLingo/courses
    command: ['tail', '-f', '/dev/null']
    ports:
      - '8000:8000' # for mkdocs serve
    #environment:
