FROM node:22-alpine

WORKDIR /root

COPY package*.json ./

COPY ./apps/answer-corrector ./apps/answer-corrector
COPY ./apps/lluis ./apps/lluis
COPY ./apps/web ./apps/web

RUN npm ci

WORKDIR /root/apps/web

CMD [ "npm", "run", "dev", "--", "--host" ]
