site_name: LibreLingo Dev Docs
repo_url: https://github.com/kantord/LibreLingo
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - bash
        - javascript
