[tool.poetry]
name = "librelingo"
version = "0.1.0"
description = ""
authors = ["Dániel Kántor <git@daniel-kantor.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-mermaid2-plugin = "^0.5.1"

[tool.poetry.dev-dependencies]
librelingo-yaml-loader = { path = "./apps/librelingo_yaml_loader/" }
librelingo-json-export = { path = "./apps/librelingo_json_export" }
librelingo-fakes = { path = "./apps/librelingo_fakes" }
librelingo-utils = { path = "./apps/librelingo_utils" }
librelingo-audios = { path = "./apps/librelingo_audios" }
pytest = "^6.2.2"
pytest-mock = "^3.5.1"
pytest-watch = "^4.2.0"
mkdocs-material = "^7.0.3"
mkdocs = "^1.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
