site_name: LibreLingo Documentation
repo_url: https://github.com/giorginogreg/LibreLingo
use_directory_urls: false
docs_dir: /LibreLingo/docs
site_dir: /LibreLingo/build/docs

theme:
  name: material
  palette:
    primary: #325f74;

plugins:
    - search
#   - mermaid2
